#! -*- perl -*-
use Kida::ToolKit::FAUtilities;
use Kida::ToolKit::Clean;

my $headers = Headers(input => [ 'Ptexture.h', 'PtexHalf.h', 'PtexUtils.h' ]);

my $libinputs = ['PtexCache.cpp',
		 'PtexFilterKernel.cpp',
		 'PtexHalf.cpp',
		 'PtexMitchellFilter.cpp',
		 'PtexReader.cpp',
		 'PtexUtils.cpp',
		 'PtexWriter.cpp'];

# can't set -pedantic by default b/c ItImage.h won't compile
# and there's no flags- to skip it just on the affected sources
#setLocalDefaults( 'CPP', 'flags+', { 'all', ['-Wall -pedantic'] } );
#setLocalDefaults( 'CPP', 'flags+', { 'all', ['-Weffc++'] } );

# manually add extra warnings to all lib sources
for (@$libinputs) { $_ = CPP(input=>$_, 'flags+' => '-Wall -pedantic'); }

my $Ptex_a = StaticLib(name	  => 'libPtex.a',
		       input 	  => $libinputs);

my $Ptex_so = SharedLib(name	   => 'libPtex.so',
			input      => $Ptex_a,
			libs       => [ '-Wl,-no-whole-archive', 'm', 'z' ],
			'flags+'   => '-Wl,-whole-archive',
			'libDirs+' => [ ]);

my $ptxmake = Exe(name => 'ptxmake', input => 'ptxmake.cpp',
		  'incDirs+' => [ "$ENV{RP_ImageToolkit}/include" ],
		  'libDirs+' => [ "$ENV{RP_ImageToolkit}/$LIB" ],
		  libs => ['ItImage', $Ptex_so->installed()]);

my $ptxinfo = Exe(name => 'ptxinfo', input => 'ptxinfo.cpp', libs => [$Ptex_so->installed()]);
my $utils = VirtualTarget( name =>'utils', input=> $ptxinfo);

my $wtest = Exe(name => 'wtest', input => 'wtest.cpp', libs => [$Ptex_so->installed()]);
my $rtest = Exe(name => 'rtest', input => 'rtest.cpp', libs => [$Ptex_so->installed()]);
my $ftest = Exe(name => 'ftest', input => 'ftest.cpp', libs => [$Ptex_so->installed()]);

my $numberfaces = SharedLib(name => 'NumberFaces.so', input=> 'NumberFaces.cpp',
			    'incDirs+' => [ "$ENV{RMANTREE}/include" ]);
my $shadeop = SharedLib(name => 'ptextureShadeop.so', input=> 'ptextureShadeop.cpp',
			'incDirs+' => [ "$ENV{RMANTREE}/include" ],
			libs => [$Ptex_so->installed()]);

my $tests = VirtualTarget( name =>'tests', input=>[ $wtest, $rtest, $ftest ]);

my $htmls = HTMLdocs(input => ['PtexFile.html'],
		     installDir => 'doc');

my $all = VirtualTarget( name =>'all',
			 input=>[ $Ptex_a, $Ptex_so, $utils, $tests, $ptxmake ]);

Install(name=>'installhdr',input=>[$headers]);

my $flavor = Kida::Exposed::getGlobalVariable('Flavor');
my $installs = [ $Ptex_a, $Ptex_so, $utils, $htmls];
if ($flavor =~ /(debug|insure)/i) {
  push(@$installs, $tests);
  push(@$installs, $ptxmake);
#  push(@$installs, $numberfaces);
#  push(@$installs, $shadeop);
}

Install(name=>'install',input=> $installs);

