Ptex: Ptex::String Class Reference
Ptex::String Class Reference
Memory-managed string.
#include <Ptexture.h>
Public Member Functions
String ()
String (const String &str)
~String ()
String & operator= (const char *str)
String & operator= (const String &str)
String & operator= (const std::string &str)
const char * c_str () const
bool empty () const
Private Attributes
char * _str
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &stream, const Ptex::String &str)
std::stream output operator.
Detailed Description
Memory-managed string.
Used for returning error messages from API functions. On most platforms, this is a typedef to std::string. For Windows, this is a custom class that implements a subset of std::string. (Note: std::string cannot be passed through a Windows DLL interface).
Definition at line 308 of file Ptexture.h.
Constructor & Destructor Documentation
String() [1/2]
Ptex::String::String () inline
Definition at line 311 of file Ptexture.h.
String() [2/2]
Ptex::String::String (const String & str) inline
Definition at line 312 of file Ptexture.h.
~String()
String::~String ()
Definition at line 673 of file PtexUtils.cpp.
Member Function Documentation
c_str()
const char* Ptex::String::c_str () const inline
Definition at line 317 of file Ptexture.h.
References _str.
Referenced by PtexWriter::edit(), PtexReaderCache::findFile(), PtexReader::open(), operator=(), and PtexWriterBase::release().
empty()
bool Ptex::String::empty () const inline
Definition at line 318 of file Ptexture.h.
References _str.
operator=() [1/3]
String & String::operator= (const char * str)
Definition at line 679 of file PtexUtils.cpp.
operator=() [2/3]
String& Ptex::String::operator= (const std::string & str) inline
Definition at line 316 of file Ptexture.h.
References c_str().
operator=() [3/3]
String& Ptex::String::operator= (const String & str) inline
Definition at line 315 of file Ptexture.h.
References _str.
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & stream, const Ptex::String & str) related
std::stream output operator.
Member Data Documentation
_str
char* Ptex::String::_str private
Definition at line 321 of file Ptexture.h.
Referenced by c_str(), empty(), and operator=().
The documentation for this class was generated from the following files:
Ptexture.h
PtexUtils.cpp