# use compiler from CXX env var if present, otherwise default to g++
ifndef CXX
CXX      = g++
LINK     = g++
else
LINK = $(CXX)
endif

CXXFLAGS = -Wall -W -pedantic -std=c++98 -fPIC

ifndef flavor
  flavor = debug
endif

ifeq ($(flavor), debug)
  CXXFLAGS += -g -DDEBUG
else
  ifeq ($(flavor), profile)
    CXXFLAGS += -O2 -pg -DNDEBUG
  else
    CXXFLAGS += -O2 -DNDEBUG
  endif
endif
